### ISSUE TITLE
Rails 4 support, why isnt it?

### ISSUE THREAD

**Issue by ktaragorn** [voormedia/rails-erd#115]
I cant install `1.2.2` cuz it depends on `~>3.2` of active record, and I use >4. Thus the max I can install is `1.1.0` and I am assuming that is why my config file is not being considered at all.

**Comment by kerrizor** [comment]
The latest release is pegged to ~>3.2 but I'll be putting out a ~>4.2 rev tomorrow.

**Comment by ktaragorn** [comment]
Hi @kerrizor would that work for 4.1 and 4.0?

**Comment by bf4** [comment]
@kerrizor do you mean you're dropping 3.x?  

```diff
- s.add_runtime_dependency "activerecord", ["~> 3.2"]
- s.add_runtime_dependency "activesupport", ["~> 3.2"]
+ s.add_runtime_dependency "activerecord", [">= 3.2", "< 5.0"]
+ s.add_runtime_dependency "activesupport", [">= 3.2", "< 5.0"]
```

like that?

**Comment by kerrizor** [comment]
I'd like to try to include 4.x rather than drop 3.x, but if it turns out we need to drop 3.x (because of changing AR internals), I was thinking of tagging a final 1.x release and branching it (as `1.x-stable`) and wrapping 4.x support into a new 2.0 release... thoughts?

**Comment by kerrizor** [comment]
In my early testing with 4.2 to ensure that its working, there's an issue with Arel::Relation being deprecated breaking `rake examples` and some subtler issues with test causing errors as well.

**Comment by bf4** [comment]
Perfect

**Comment by kerrizor** [comment]
Update - I'm at CodeMash right now, and struggling a bit to untangle some 4.2 conflicts in the test suite. While I'm confident the gem itself works reasonably well under 4.x, without tests working I'm not comfortable releasing it into the wild. I've got 12 more tests to address (looks like maybe 3 different issues in AR internals changing..) and I'll have something to share with the class.

**Comment by ktaragorn** [comment]
I forked my own just to try.. I am still not able to get config files working right.. They appear to be read but the erd output doesnt show it. I can get the `--attributes` to work on cli, but not `--exclude` as already reported in https://github.com/voormedia/rails-erd/issues/50 . Tried to search for `exclude` in the code, didnt get anything promising..

**Comment by ktaragorn** [comment]
One feature request, I can make it a seperate ticket if interested, If keys are shown, they should be emphasized or differentiated in some way.

**Comment by KazW** [comment]
Found this while looking for fixes, it works for me: https://github.com/ready4god2513/rails-erd/tree/rails-4.2-support-fix

**Comment by kerrizor** [comment]
Yes it works, but adding it to the gem as a whole causes some other issues,
so I'm trying to balance that:(

**Comment by bf4** [comment]
@kerrizor I don't have it running, but from [the basic idea of the patch](https://github.com/ready4god2513/rails-erd/commit/3c0e0b93452392651df7daaf8678b2bb9aa8faf1.patch) is

```ruby
# lib/rails_erd/domain/attribute.rb
 
       # Returns +true+ if this attribute is the primary key of the entity.
       if Rails.method_defined?(:version)
         def primary_key?
           @model.primary_key == column.name
         end
       else
         def primary_key?
           column.primary
         end
       end
```

which should be pretty safe since [Rails.version was introducted in 4.2](https://github.com/rails/rails/commit/2dd2fcf89673afbcf95240ecebaf34826a195164). Otherwise I suppose `if Rails::VERSION::STRING >= '4.2'`

**Comment by kerrizor** [comment]
The problem I ran into a was getting tests sorted, since they're relying on
AR internals for set up

**Comment by florisvlasveld** [comment]
Hi @kerrizor, thanks so much for looking into this. Do you have any news regarding the tests? I'd love to use Rails ERD in a Rails 4 production environment.

**Comment by ccmcbeck** [comment]
I'll second that.  I'm waiting to have the walkthrough on my schema design until I can use ERD to produce the diagrams.  :-)

**Comment by bf4** [comment]
@kerrizor might be worth making a `pre` release to get something out.

**Comment by ferrance** [comment]
I was having the null specialization bug that was fixed in 1.2.0, but couldn't install 1.2.0 because I'm on Rails 4.  Ended up patching my local copy of 1.1.0 and can generate ERDs now.

**Comment by a2ikm** [comment]
@kerrizor  I'm trying to support rails 4 but some tests are still failing. I'm happy if you refer that.

https://github.com/a2ikm/rails-erd/tree/support_rails_4.x
https://travis-ci.org/a2ikm/rails-erd/

**Comment by kerrizor** [comment]
@a2ikm As you found, getting it to support Rails 4.x isn't difficult, its getting the test suite passing.

@bf4 - that's a solid idea!

**Comment by kerrizor** [comment]
Thanks to @a2ikm in #120 we now have Rails 4.x support. Thank you for the heavy lifting!

**Comment by florisvlasveld** [comment]
That's great, thanks a lot @a2ikm & @kerrizor.

**Comment by johannesE** [comment]
Am I missing something here or why does the readme still only mention rails 3 one year after this?

**Comment by kerrizor** [comment]
@johannesE 

> Rails ERD was created specifically for Rails and works on versions 3.0-4.2.

I see there's a fair bit of improvement to be made in documentation here. I'll make sure we're tracking that as an issue. Thanks!
